---
- name: ping all hosts
  hosts: all
  become: false

  tasks:
    - name: show some info
      debug:
        msg:
          - Hostname   = {{ ansible_facts['hostname'] }}
          - IP address = {{ ansible_facts['default_ipv4']['address'] }}

    - name: just ping
      ping:
