name: ansible-lint
on: [push]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: linter
    steps:
      - uses: actions/checkout@v3
      - run: |
        date > generated.txt
        /usr/local/bin/yamllint
        /usr/local/bin/ansible-lint
