name: ansible-lint
on: [push]
jobs:
  check-ansible-code:
    name: Ansible Lint
    runs-on: linter
    steps:
      - uses: actions/checkout@v3
      - run: /usr/local/bin/yamllint *.yml
      - run: /usr/local/bin/ansible-lint

