---
name: ansible-lint
on: [push]

jobs:
  check-ansible-code:
    name: Ansible Lint
    runs-on: linter
    steps:
      - uses: actions/checkout@v3
      - run: /usr/local/bin/yamllint *.yml
      - run: /usr/local/bin/ansible-lint
  fire_and_forget:
    name: Trigger playbook in AAP
    runs-on: linter
    steps:
      - run: |
          curl -k -f -i
          -H 'Content-Type:application/json'
          -XPOST -d '{"host_config_key": "q0jUeNCqP2PPZh8jIGdSCHYHCUgZuA"}'
          https://aap.ansilab.nl/api/v2/job_templates/11/callback/

