name: ansible-lint
on: [push]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: linter
    steps:
      - name: Run ansible-lint
        uses: "https://git.ansilab.nl/tonk/ping.git"
