---
name: system_provisioning
on: [push]            # yamllint disable-line rule:truthy

jobs:
  check-ansible-code:
    name: Run linters
    runs-on: runner
    steps:
      - uses: actions/checkout@v3
      - run: /usr/local/bin/yamllint *.yml
      - run: /usr/local/bin/ansible-lint

  fire_and_forget:
    name: Trigger provisioning playbook in AWX
    runs-on: runner
    steps:
      - run: >
          curl -k -f -i
          -H 'Content-Type:application/json'
          -XPOST -d '{"host_config_key": "<Host Config Key>"}'
          http://awx.ansiblelab.nl/api/v2/job_templates/<Template ID>/callback
